const labels: Record<string, string> = {
  bucket: '分组',
  trade_count: '交易数',
  win_count: '盈利数',
  loss_count: '亏损数',
  win_rate: '胜率',
  net_pnl: '净盈亏',
  net_return: '净收益率',
  average_pnl: '平均盈亏',
  average_holding_seconds: '平均持仓时间',
  holding_bucket: '持仓时间区间',
  pnl_bucket: '盈亏金额区间',
  fill_bucket: '成交档位',
  tier: '档位',
  symbol: '交易对',
  parameters: '参数',
  run_id: '运行 ID',
  breakout_window_hours: '上涨窗口',
  rise_trade_count: '上涨后交易数',
  rise_win_rate: '上涨后胜率',
  rise_net_pnl: '上涨后净盈亏',
  collision_group_id: '竞争组 ID',
  collision_size: '竞争单数',
  independent_pnl: '独立净盈亏',
  conservative_pnl: '保守净盈亏',
  signal_time: '信号时间',
  signal_time_iso: '信号时间',
  entry_time: '开仓时间',
  entry_time_iso: '开仓时间',
  exit_time: '退出时间',
  exit_time_iso: '退出时间',
  entry_price: '开仓价格',
  exit_price: '退出价格',
  average_entry_price: '开仓均价',
  entry_quantity: '开仓数量',
  exit_quantity: '退出数量',
  entry_fill_count: '开仓成交笔数',
  exit_fill_count: '退出成交笔数',
  exit_reason: '退出原因',
  status: '状态',
  winner: '是否盈利',
  side: '方向',
  campaign_id: '交易批次',
  trade_id: '交易 ID',
  tier1_price: '第一档价格',
  tier2_price: '第二档价格',
  tier3_price: '第三档价格',
  tier1_weight: '第一档权重',
  tier2_weight: '第二档权重',
  tier3_weight: '第三档权重',
  tier1_fill_count: '第一档成交数',
  tier2_fill_count: '第二档成交数',
  tier3_fill_count: '第三档成交数',
  tier1_avg_fill_price: '第一档成交均价',
  tier2_avg_fill_price: '第二档成交均价',
  tier3_avg_fill_price: '第三档成交均价',
  invalid_price: '失效价格',
  trigger_price: '触发价格',
  prior_high: '前期高点',
  prior_high_4h: '4 小时前高',
  low_4h: '4 小时低点',
  low_6h: '6 小时低点',
  low_8h: '8 小时低点',
  low_12h: '12 小时低点',
  low_24h: '24 小时低点',
  rise_from_4h_low: '相对 4 小时低点涨幅',
  rise_from_6h_low: '相对 6 小时低点涨幅',
  rise_from_8h_low: '相对 8 小时低点涨幅',
  rise_from_12h_low: '相对 12 小时低点涨幅',
  rise_from_24h_low: '相对 24 小时低点涨幅',
  box_3d_position: '3 天箱体位置',
  box_7d_position: '7 天箱体位置',
  holding_seconds: '持仓秒数',
  collision_status: '交易竞争状态',
}

const tokens: Record<string, string> = {
  atr: 'ATR',
  avg: '平均',
  entry: '开仓',
  exit: '退出',
  notional: '名义金额',
  box: '箱体',
  high: '高点',
  low: '低点',
  valid: '有效',
  days: '天数',
  bucket: '分组',
  campaign: '批次',
  chunk: '分块',
  hours: '小时',
  hour: '小时',
  minutes: '分钟',
  minute: '分钟',
  seconds: '秒数',
  second: '秒',
  collision: '竞争',
  conservative: '保守',
  independent: '独立',
  pnl: '盈亏',
  net: '净',
  gross: '毛',
  commission: '手续费',
  data: '数据',
  incomplete: '不完整',
  database: '数据库',
  allowed: '允许',
  details: '详情',
  estimate: '估算',
  estimated: '预计',
  materialized: '物化',
  stream: '流',
  peak: '峰值',
  end: '结束',
  start: '开始',
  time: '时间',
  action: '动作',
  fill: '成交',
  filled: '已成交',
  count: '数量',
  pattern: '形态',
  price: '价格',
  quantity: '数量',
  policy: '策略',
  protected: '保护',
  reason: '原因',
  rise: '上涨',
  drop: '下跌',
  return: '收益率',
  trade: '交易',
  trades: '交易数',
  final: '最终',
  total: '总计',
  first: '首个',
  last: '最后',
  ms: '毫秒',
  usdt: 'USDT',
  giveback: '回撤',
  has: '具备',
  archive: '归档',
  hit: '触及',
  stop: '止损',
  holding: '持仓',
  invalid: '失效',
  loss: '亏损',
  path: '路径',
  category: '分类',
  adverse: '不利',
  favorable: '有利',
  max: '最大',
  min: '最小',
  median: '中位数',
  volume: '成交量',
  duration: '持续时间',
  month: '月份',
  baseline: '基线',
  original: '原始',
  parameters: '参数',
  position: '位置',
  prior: '前期',
  lookback: '回看',
  profit: '盈利',
  factor: '因子',
  pullback: '回撤',
  qty: '数量',
  rows: '行数',
  run: '运行',
  runs: '运行数',
  scaled: '缩放后',
  selected: '已选择',
  side: '方向',
  signal: '信号',
  cooldown: '冷却',
  simultaneous: '同时',
  spike: '尖峰',
  definition: '定义',
  strategy: '策略',
  symbol: '交易对',
  symbols: '交易对数',
  threshold: '阈值',
  triggered: '已触发',
  trigger: '触发',
  window: '窗口',
  winner: '是否盈利',
  wins: '盈利数',
  win: '盈利',
  tier: '档位',
  tier1: '第一档',
  tier2: '第二档',
  tier3: '第三档',
  '1s': '1秒',
  '1m': '1分钟',
  '5m': '5分钟',
  '15m': '15分钟',
  '3d': '3天',
  '7d': '7天',
  '4h': '4小时',
  '6h': '6小时',
  '8h': '8小时',
  '12h': '12小时',
  '24h': '24小时',
  origin: '起涨点',
  order: '订单',
  ttl: '有效期',
  weight: '权重',
  status: '状态',
  event: '事件',
  strategy_id: '策略 ID',
  run_id: '运行 ID',
}

export function reportLabel(key: string): string {
  if (labels[key]) return labels[key]
  const translated = key.split('_').map((part) => tokens[part.toLowerCase()] || part)
  return translated.some((part, index) => part !== key.split('_')[index]) ? translated.join('') : '字段'
}

export function hasReportLabel(key: string): boolean {
  return reportLabel(key) !== '字段'
}
